#!/bin/sh

echo $0 $@
echo "flashrom v0.9.9-55-g75a2a79 on Linux 4.11.12-sun8i (armv7l)"
echo "flashrom is free software, get the source code at https://flashrom.org"
sleep 2
echo "Using clock_gettime for delay loops (clk_id: 1, resolution: 1ns)."
echo "Found Winbond flash chip "W25Q64.V" (8192 kB, SPI) on linux_spi."
echo -n "Reading old flash chip contents... "; sleep 3; echo "done."
echo -n "Erasing and writing flash chip... "; sleep 3; echo "Erase/write done."
echo -n "Verifying flash... "; sleep 3; echo #"VERIFIED."
